version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - '5000:5000'
    volumes:
      - ./backend:/app
    networks:
      - my-network
    environment:
      - MONGO_DB_URI=mongodb://mongo:27017/mydatabase

  frontend:
    build:
      context: ./frontend
    ports:
      - '5173:5173'
    volumes:
      - ./frontend:/app
    networks:
      - my-network

  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
    networks:
      - my-network

networks:
  my-network:

volumes:
  mongo-data:
